# Generated by Django 3.2.25 on 2024-06-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_value', models.DecimalField(decimal_places=6, max_digits=11)),
                ('rate_date', models.DateField(unique=True)),
            ],
            options={
                'db_table': 'currency_rate',
            },
        ),
    ]
