# Generated by Django 3.2.25 on 2024-06-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrate',
            name='rate_date',
            field=models.DateField(db_index=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='currencyrate',
            index=models.Index(fields=['rate_date'], name='currency_ra_rate_da_551e5d_idx'),
        ),
    ]
